apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: zlj1l4ekt-python-gitops
  description: This is GitOps manifest for zlj1l4ekt-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: zlj1l4ekt-python
    janus-idp.io/tekton: zlj1l4ekt-python 
    backstage.io/kubernetes-id: zlj1l4ekt-python 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:zlj1l4ekt-python
