apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: zlj1l4ekt-python
  janus-idp.io/tekton: zlj1l4ekt-python
  backstage.io/kubernetes-id: zlj1l4ekt-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zlj1l4ekt-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
