apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: zlj1l4ekt-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: zlj1l4ekt-python 
  name: zlj1l4ekt-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: zlj1l4ekt-python 
